---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: tetris
        image: papuganivijaykumar/node:v67
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: project-service
spec:
  selector:
    app: project
  ports:
    - port: 80                 # Expose port 80
      targetPort: 3000
      nodePort: 30001
  type: NodePort
